/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-11 06:09:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Mtest/workSpring/my/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sts0810/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Mtest/workSpring/my/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sts0810/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1691655740225L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>[boardWrite.jsp]</title>\n");
      out.write("   <style type=\"text/css\">\n");
      out.write("    *{font-size: 16pt; font-weight: bold; }\n");
      out.write("    a{text-decoration:none; font-weight: bold;   color:blue ;}\n");
      out.write("    a:hover{font-size: 20pt; font-weight: bold;   text-decoration:underline; color:green ;  }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write(" <font color=blue>[boardWrite.jsp]</font> <br>\n");
      out.write("\n");
      out.write("  <form  action=\"boardInsert.do\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("      이름: <input type=\"text\" name=\"name\" value=\"kim\"> <br>\n");
      out.write("      제목: <input type=\"text\" name=\"title\" value=\"blue\"> <br>\n");
      out.write("      내용: <textarea rows=\"3\" cols=\"20\"  name=\"content\">test</textarea> <br>\n");
      out.write("      성별:\n");
      out.write("      <input type=\"radio\" name=\"gender\" value=\"man\" checked>남자 \n");
      out.write("      <input type=\"radio\" name=\"gender\" value=\"woman\">여자 <br>\n");
      out.write("      취미:\n");
      out.write("      <input type=\"checkbox\" name=\"hobby\" value=\"game\">게임\n");
      out.write("      <input type=\"checkbox\" name=\"hobby\" value=\"study\">공부\n");
      out.write("      <input type=\"checkbox\" name=\"hobby\" value=\"ski\">스키\n");
      out.write("      <input type=\"checkbox\" name=\"hobby\" value=\"movie\" checked>영화 <br>\n");
      out.write("      파일: <input type=\"file\" name=\"upload_f\"><br>\n");
      out.write("      <input type=\"submit\" value=\"스프링hobby테이블저장\">\n");
      out.write("      <input type=\"reset\" value=\"입력취소\">\n");
      out.write("  </form>  \n");
      out.write("  \n");
      out.write("   <p>\n");
      out.write(" 	<a href=\"index.jsp\">[index.jsp]</a>\n");
      out.write("    <a href=\"boardWrite.do\">[게시판등록]</a>\n");
      out.write("    <a href=\"boardList.do\">[전체출력]</a> \n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<!-- -\n");
      out.write(" <form  action=\"boardInsert.do\"   method=\"post\" enctype=\"multipart/form-data\"  >\n");
      out.write("\n");
      out.write(" 파일: <input type=\"file\" name=\"upload_f\"><br>\n");
      out.write("    \n");
      out.write(" -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
